FROM python:3.10.4

# Install rsync
RUN apt-get update && \
    apt-get install -y rsync findutils && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY ./requirements.txt /app/requirements.txt

RUN pip install -r /app/requirements.txt

WORKDIR /app